name: CI / Check Base Image

on:
  workflow_dispatch:
  schedule:
    # Run every Sunday at a 1:13 ("random" time)
    - cron:  '13 1 * * 0'

env:
  IMAGE_NAME: ddclient

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: read
    outputs:
      needs-updating: ${{ steps.scan-image.outputs.needs-updating }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Grep base image from Dockerfile
        id: base
        env:
          DOCKERFILE: "./Dockerfile"
        run: |
          set -e
          BASE="$(grep "FROM" "${DOCKERFILE}" | tail -1 | awk '{print $2}')"
          echo "image=${BASE#cli-}" >> "$GITHUB_OUTPUT"

      - name: Check if base image changed
        # Only supports docker.io
        uses: lucacome/docker-image-update-checker@f50d56412b948cfdbb842c5419372681e0db3df1 # v1.2.1
        id: scan-image
        with:
          base-image: "${{ steps.base.outputs.image }}"
          image: "${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest"
          platforms: linux/amd64,linux/arm64

  rebuild:
    uses: ./.github/workflows/build-container.yaml
    needs: scan
    if: needs.scan.outputs.needs-updating == 'true'
    permissions:
      contents: read
      packages: write
    secrets: inherit
