---
name: "Editorconfig Check"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  check-editorconfig:
    name: Run editorconfig-checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Run editorconfig-checker
        uses: docker://mstruebing/editorconfig-checker:2.7.1
        with:
          args: ec --exclude=".git/*"
